name: briancristian
favicon: null
layout_spectrum: 0.18777727312408388
typography_spectrum: 0.27993400767445564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.07593360892497003
  lightness: 0.5055433332454413
  saturation: 0.7342244395986199
  rhythmicContrast: 0.587087465217337
purpose: []
